EM-aspcore/Models/EmployeeViewModel.cs
using EmAspCore.Entity;
using System.Collections.Generic;

namespace EmAspCore.Models
{
    public class EmployeeViewModel
    {
        // 検索結果の格納
        public List<Employee> employees { get; set; }
        public List<Department> departments { get; set; }
    }
}

EM-aspcore/Models/ErrorViewModel.cs
using System;

namespace EmAspCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EM-aspcore/Models/LoginModel.cs
namespace EmAspCore.Models
{
    public class LoginModel
    {
    }
}

EM-aspcore/Controllers/EmployeeController.cs
using EmAspCore.Models;
using EmAspCore.Services;
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            EmployeeViewModel model = new EmployeeViewModel();

            // 初期表示用に検索をしておく
            SearchService service = new SearchService();

            // Modelに詰める
            model.employees = service.SelectAllEmployee();
            model.departments = service.SelectAllDepartment();

            return View(model);
        }
    }
}

EM-aspcore/Controllers/HomeController.cs
using System.Diagnostics;
using EmAspCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EM-aspcore/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class LoginController : Controller
    {
        /*
         *  ~/Login　でアクセスする
         * 
         */

        public IActionResult Index()
        {
            return View();
        }

        /*
         * ~/Login/Hello　でアクセスする
         * 
         */
        public string Hello()
        {
            return "とりあえずこれが表示されるならOK？";
        }
    }
}

EM-aspcore/Controllers/MenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace EmAspCore.Controllers
{
    public class MenuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EM-aspcore/Views/Employee/Index.cshtml
@model EmployeeViewModel

@{
    ViewData["Title"] = "List";
}

<h2>List</h2>

<p>
    <a  href="#updateModal" data-toggle="modal" onclick="reflectDialog(null)">Create New</a>
</p>
<table class="table table-hover" id="searchResult">
    <thead>
        <tr>
        <tr>
            <th>社員ID</th>
            <th>社員名</th>
            <th>フリガナ</th>
            <th>メールアドレス</th>
            <th>パスワード</th>
            <th>所属部署</th>
            <th>削除</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model.employees)
        {
            <tr>
                <td>
                    <a href="#updateModal" data-toggle="modal"
                       onclick="reflectDialog(@emp.employeeId)">@emp.employeeId</a>
                <td>@emp.employeeName</td>
                <td>@emp.employeeKana</td>
                <td>@emp.mailAddress</td>
                <td>@emp.password</td>
                @foreach (var dep in Model.departments)
                {
                    if (emp.departmentId == dep.departmentId)
                    {
                        <td>@dep.departmentName</td>
                        break;
                    }
                }
                <td>
                    <a href="#deleteModal" data-toggle="modal"
                       onclick="reflectDelDialog(@emp.employeeId)">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="updateModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">ユーザ情報－<span id="mode"></span></h4>
            </div>
            <div class="modal-body">
                <div id="updErrors"></div>
                <form action="updateEmp" id="update" name="updateform"
                      class="form-horizontal" method="post">
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="updateInput_empId">社員ID</label>
                        <div class="col-xs-5">
                            <input type="text" name="empId" id="Input_empId" readonly class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_empNm">社員名</label>
                        <div class="col-xs-5">
                            <input type="text" name="empNm" placeholder="社員名" id="Input_empNm"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_empKn">フリガナ</label>
                        <div class="col-xs-5">
                            <input type="text" name="empKn" placeholder="フリガナ" id="Input_empKn"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label" for="Input_mail">メールアドレス</label>
                        <div class="col-xs-5">
                            <input type="text" name="mail" placeholder="メールアドレス" id="Input_mail"
                                   class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="updateInput_changePass">パスワード</label>
                        <div class="col-xs-5">
                            <input type="password" name="changePass" placeholder="パスワード"
                                   class="form-control" />
                        </div>
                        <span class="help-block text-center" id="passTopic">※変更しない場合は未入力</span>
                        <input type="hidden" id="Input_pass" name="pass" />
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="Input_passConfirm">再入力</label>
                        <div class="col-xs-5">
                            <input type="password" name="Input_passConfirm"
                                   placeholder="再入力" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-3 control-label"
                               for="updateInput_department">所属部署</label>
                        <div class="col-xs-5">
                            <select name="department" id="Input_department" onchange="departmentChange();" class="form-control">
                                @foreach (var dep in Model.departments)
                                {
                                    <option value="@dep.departmentId">@dep.departmentName</option>
                                }
                            </select>
                            <input type="hidden" id="Input_depId" name="depId" />
                            <input type="hidden" id="Input_depNm" name="depNm" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" id="btnRegist"
                        onclick="executeUpdate()">
                    更新
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // グローバル変数
    var existsInsError = false;

    // 各ダイアログでの処理
    function departmentChange() {
        $("#Input_depId").val($("#Input_department").val());
        $("#Input_depNm").val($("#Input_department option:selected").text());
    }

    // キー情報の取り込み処理
    function reflectDialog(target) {
        // 入力項目の初期化
        modalInit();


        if (target == null) {
            // 新規登録用モーダル
            $("#mode").text("登録");
            $("#Input_empId").val("IDは自動で割り振られます");
            $("#passTopic").css("visibility", "hidden")

        } else {
            // 更新用モーダル
            $("#mode").text("更新");
            $("#passTopic").css("visibility", "visible")

            $("#Input_empId").val(target);

            // 検索しないで画面のある行からデータを反映
            $("#searchResult tbody tr").each(function () {
                var id = $(this).find("td:nth-child(1)").text();
                if (parseInt(id) == target) {
                    $("#Input_empNm").val($(this).find("td:nth-child(2)").text());
                    $("#Input_empKn").val($(this).find("td:nth-child(3)").text());
                    $("#Input_mail").val($(this).find("td:nth-child(4)").text());
                    $("#Input_pass").val($(this).find("td:nth-child(5)").text());
                    //名称を設定
                    $("#Input_depNm").val($(this).find("td:nth-child(6)").text());
                    //名称から値を取得
                    $("#Input_department option").each(function () {
                        if ($("#Input_depNm").val() == $(this).text()) {
                            $("#Input_depId").val($(this).val());
                        }
                    });
                    //コンボボックスを設定
                    $("#Input_department").val($("#Input_depId").val());
                }
            });
        }
    }

    function modalInit() {
        $("#Input_empId").val('');
        $("#Input_empNm").val('');
        $("#Input_empKn").val('');
        $("#Input_mail").val('');
        $("#Input_depNm").val('');
        $("#Input_department").val('10');
    }
</script>

EM-aspcore/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

EM-aspcore/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

EM-aspcore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

EM-aspcore/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EM-aspcoreログイン</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12"></div>
        </div>
        <div class="row">
            <div class="col-xs-offset-3 col-xs-6">
                <div class="panel panel-info">
                    <div class="panel-body">
                        <h3 class="text-center">ログイン</h3>
                        <span class="help-block text-center">yamada@hoge.jp / aaa でログインできます。</span>

                        <c:out value="${message}" />

                        <form action="login" class="form-horizontal" method="post">
                            <div class="form-group">
                                <label class="col-xs-4 control-label" for="mail">メールアドレス</label>
                                <div class="col-xs-8">
                                    <input type="text" required placeholder="メールアドレス"
                                           class="form-control" name="mail" value="${mail}" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-xs-4 control-label" for="pass">パスワード</label>
                                <div class="col-xs-8">
                                    <input type="password" name="pass" required placeholder="パスワード"
                                           class="form-control" value="${pass}" />
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-offset-5 col-xs-2">
                                    <input type="submit" value="ログイン" class="btn btn-info" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
</body>
</html>

EM-aspcore/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

EM-aspcore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EM_aspcore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Menu" asp-action="Index" class="navbar-brand">EM-System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Menu" asp-action="Index">ホーム</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="Index">社員検索</a></li>
                    <li><a asp-area="" asp-controller="Department" asp-action="Index">部署検索</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EM_aspcore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>